version: '3.8'

services:
  backend:
    build: ./backend
    container_name: flyingo_api
    ports:
      - "5101:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/flyingo
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
    depends_on:
      - mongodb
      - redis

  frontend:
    build: ./frontend
    container_name: flyingo_ui
    ports:
      - "3101:3000"
    environment:
      - WDS_SOCKET_PORT=3101
    stdin_open: true
    tty: true
    depends_on:
      - backend

  mongodb:
    image: mongo:4.4
    container_name: flyingo_db
    ports:
      - "27101:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:6.2-alpine
    container_name: flyingo_redis
    ports:
      - "6401:6379"

volumes:
  mongodb_data:
